displayName=Ping Check
author=jaesicc
description=Plugin that let's you configure a ping threshold that will notify you before entering certain PvM content
tags=ping,check,enter,toa,gauntlet,tob,cox,zulrah,vorkath,dt2,vardorvis,duke,leviathan,whisperer
version=
plugins=com.pingcheck.PingCheckPlugin
build=standard
support=https://github.com/jaesicc/ping-check